apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: wanderlust
data:
  PORT: "8080"
  FRONTEND_URL: "http://frontend-service:5173"
  ACCESS_COOKIE_MAXAGE: "120000" 
  ACCESS_TOKEN_EXPIRES_IN: "120s"
  REFRESH_COOKIE_MAXAGE: "120000"
  REFRESH_TOKEN_EXPIRES_IN: "120s"
  NODE_ENV: "Development"
