@Library('Shared') _
pipeline {
    agent any
    
    parameters {
        string(name: 'FRONTEND_DOCKER_TAG', defaultValue: '', description: 'Frontend Docker tag of the image built by the CI job')
        string(name: 'BACKEND_DOCKER_TAG', defaultValue: '', description: 'Backend Docker tag of the image built by the CI job')
    }

    stages {
        stage("Workspace Cleanup") {
            steps {
                script {
                    cleanWs()
                }
            }
        }
        
        stage('Git: Code Checkout') {
            steps {
                script {
                    code_checkout("https://github.com/Roshanx96/Wanderlust-Mega-Project.git", "main")
                }
            }
        }
        
        stage('Verify: Docker Image Tags') {
            steps {
                script {
                    echo "FRONTEND_DOCKER_TAG: ${params.FRONTEND_DOCKER_TAG}"
                    echo "BACKEND_DOCKER_TAG: ${params.BACKEND_DOCKER_TAG}"
                }
            }
        }
        
        stage("Update: Kubernetes Manifests") {
            steps {
                script {
                    dir('kubernetes') {
                        sh """
                            sed -i -E 's|(image: .*wanderlust-backend-beta:).*|\\1${params.BACKEND_DOCKER_TAG}|' backend.yaml
                            sed -i -E 's|(image: .*wanderlust-frontend-beta:).*|\\1${params.FRONTEND_DOCKER_TAG}|' frontend.yaml
                        """
                    }
                }
            }
        }
        
        stage("Git: Commit & Push Changes") {
            steps {
                script {
                    withCredentials([gitUsernamePassword(credentialsId: 'Github-cred', gitToolName: 'Default')]) {
                        sh '''
                        echo "Setting Git User Identity"
                        git config --global user.email "roshankhopade5339@gmail.com"
                        git config --global user.name "Roshanx96"

                        echo "Checking repository status: "
                        git status

                        echo "Adding changes to git: "
                        git add .

                        echo "Committing changes: "
                        git commit -m "Updated Kubernetes manifests with new image tags" || echo "No changes to commit"

                        echo "Pushing changes to GitHub: "
                        git push origin main
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            script {
                emailext attachLog: true,
                from: 'roshankhopade5339@gmail.com',
                subject: "Wanderlust Application Successfully Deployed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                        <div style="background-color: #87CEEB; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">URL: ${env.BUILD_URL}</p>
                        </div>
                    </body>
                    </html>
                """,
                to: 'roshankhopade5339@gmail.com',
                mimeType: 'text/html'
            }
        }

        failure {
            script {
                emailext attachLog: true,
                from: 'roshankhopade5339@gmail.com',
                subject: "Wanderlust Application Deployment Failed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                        <div style="background-color: #FF6347; padding: 10px; margin-bottom: 10px;">
                            <p style="color: white; font-weight: bold;">Check Jenkins logs for details.</p>
                        </div>
                    </body>
                    </html>
                """,
                to: 'roshankhopade5339@gmail.com',
                mimeType: 'text/html'
            }
        }
    }
}
